apiVersion: v1
kind: Service
metadata:
  name: {{ include "back-helm.fullname" . }}
  labels:
    {{- include "back-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: 
    app: backend
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "back-helm.selectorLabels" . | nindent 4 }}
